name: Test and lint
on: [push]
env:
  PYTHONPATH: .
jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: "3.9"
      - run: pip install pipenv
      - name: Cache virtualenvs
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs/
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
      - run: pipenv sync --dev
      - run: pipenv run pytest
      - run: pipenv run ./scripts/format_check.sh
